### ISSUE TITLE
How can I install in anaconda virtual environment ?

### ISSUE THREAD

**Issue by boxerab** [ROCmSoftwarePlatform/tensorflow#11]
I got this working on ubuntu 16 with rocm 1.7.1 rc 7, with python2. 
But, when I create a virtual anaconda environment with python 2, tensorflow is not found. 
Is there a way of installing into virtual env ?

Many users are working with anaconda and tensorflow.

**Comment by boxerab** [comment]
Also wondering about other virtual environments such as `virtualenv`

**Comment by sunway513** [comment]
@boxerab , we only have passthrough on KVM for virtual environment support.

**Comment by boxerab** [comment]
@sunway513 thanks. by virtual, I mean just a virtual software environment.

**Comment by boxerab** [comment]
not a virtualized OS

**Comment by whchung** [comment]
@boxerab Thanks for your clarification, we normally work under bare metal or within docker containers. virtualenv or conda is less used by the working team. I'm wondering could you help provide errors / steps you try use the pip wheel package within those environments?

**Comment by boxerab** [comment]
@whchung  thanks, everything works fine on anaconda by, as you suggest, pip installing the wheel package in that environment.
