### ISSUE TITLE
Getting HIP_ERROR with latest whl file under python 2.7

### ISSUE THREAD

**Issue by boxerab** [ROCmSoftwarePlatform/tensorflow#14]
2018-03-22 18:14:41.893382: E tensorflow/stream_executor/rocm/rocm_driver.cc:1098] could not retrieve ROCM device count: HIP_ERROR_NoDevice

Running this sample:

https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/2_BasicModels/kmeans.py

**Comment by sclarkson** [comment]
If you're running headless, or otherwise without an X session, make sure you're in the video group.

ctrl+F video on here https://rocm.github.io/ROCmInstall.html

After adding yourself to the group, you can either relog or run `sg video`

**Comment by whchung** [comment]
@boxerab commenting out line #19-#20 of said URL removes the error. It seems the test actually tries to ignore GPU.

**Comment by boxerab** [comment]
Thanks. But, why does the error occur ?

**Comment by whchung** [comment]
The test explicitly disables all GPUs in the runtime. StreamExecutor therefore couldn't retrieve "the current GPU" and thus raise the error.

**Comment by boxerab** [comment]
Great, thanks!
