### ISSUE TITLE
Questions regarding 'Tensorflow ROCm port: Basic installation' (2 questions)

### ISSUE THREAD

**Issue by xyang2013** [ROCmSoftwarePlatform/tensorflow#18]
Thanks in advance

Question 1

For Python 3, in the 'Install required python packages', should I install the associated Python 3 packages?

Question 2

In 'Build and install hcfft", I had an error and am not sure whether it is critical:

> cd ~/hcfft && bash build.sh && sudo dpkg -i ~/hcfft/build/*.deb
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /opt/rocm/hcc/bin/clang
-- Check for working C compiler: /opt/rocm/hcc/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rocm/hcc/bin/clang++
-- Check for working CXX compiler: /opt/rocm/hcc/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE VERSION 3.5.1
-- PROJECT NAME    : hcfft
HIP_PATH=/opt/rocm/hip
-- Found HC++: /opt/rocm/hcc/bin (Required is at least version "1.0") 
-- HC++ Compiler found in /opt/rocm/hcc/bin/..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xyang/hcfft/build
Scanning dependencies of target hipfft
Scanning dependencies of target hcfft
[  5%] Building CXX object lib/src/CMakeFiles/hipfft.dir/hcfft.cpp.o
[ 10%] Building CXX object lib/src/CMakeFiles/hipfft.dir/generator.transpose.nonsquare.cpp.o
[ 21%] Building CXX object lib/src/CMakeFiles/hipfft.dir/transform.cpp.o
[ 21%] Building CXX object lib/src/CMakeFiles/hipfft.dir/generator.copy.cpp.o
[ 26%] Building CXX object lib/src/CMakeFiles/hipfft.dir/generator.transpose.cpp.o
[ 31%] Building CXX object lib/src/CMakeFiles/hipfft.dir/generator.stockham.cpp.o
[ 36%] Building CXX object lib/src/CMakeFiles/hipfft.dir/generator.transpose.gcn.cpp.o
[ 42%] Building CXX object lib/src/CMakeFiles/hcfft.dir/hcfft.cpp.o
[ 47%] Building CXX object lib/src/CMakeFiles/hcfft.dir/generator.transpose.nonsquare.cpp.o
[ 52%] Building CXX object lib/src/CMakeFiles/hipfft.dir/generator.transpose.square.cpp.o
[ 57%] Building CXX object lib/src/CMakeFiles/hcfft.dir/generator.transpose.cpp.o
[ 63%] Building CXX object lib/src/CMakeFiles/hcfft.dir/transform.cpp.o
[ 68%] Building CXX object lib/src/CMakeFiles/hcfft.dir/generator.copy.cpp.o
[ 73%] Building CXX object lib/src/CMakeFiles/hcfft.dir/generator.transpose.gcn.cpp.o
[ 78%] Building CXX object lib/src/CMakeFiles/hipfft.dir/hcc_detail/hipfft.cpp.o
[ 84%] Building CXX object lib/src/CMakeFiles/hcfft.dir/generator.stockham.cpp.o
[ 89%] Building CXX object lib/src/CMakeFiles/hcfft.dir/generator.transpose.square.cpp.o
[ 94%] Linking CXX shared library libhipfft.so
Invalid bitcast
%struct.tile addrspace(1)* bitcast (i64 addrspace(2)* @_ZL6lwSize to %struct.tile addrspace(1)*)
/opt/rocm/hcc/bin/llvm-link: error: linked module is broken!
[ 94%] Built target hipfft
[100%] Linking CXX shared library libhcfft.so
Invalid bitcast
%struct.tile addrspace(1)* bitcast (i64 addrspace(2)* @_ZL6lwSize to %struct.tile addrspace(1)*)
/opt/rocm/hcc/bin/llvm-link: error: linked module is broken!
[100%] Built target hcfft
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: Project
CPack: - Install project: Project
CPack: Create package
CPack: - package: /home/xyang/hcfft/build/hcfft-master-47ee790-Linux.deb generated.
CPack: Create package using TGZ
CPack: Install projects
CPack: - Run preinstall target for: Project
CPack: - Install project: Project
CPack: Create package
CPack: - package: /home/xyang/hcfft/build/hcfft-master-47ee790-Linux.tar.gz generated.
[ 47%] Built target hcfft
[100%] Built target hipfft
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /opt/rocm/hcc/bin/clang
-- Check for working C compiler: /opt/rocm/hcc/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rocm/hcc/bin/clang++
-- Check for working CXX compiler: /opt/rocm/hcc/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xyang/hcfft/build/packaging
HCFFT Installation Completed!
Selecting previously unselected package hcfft.
(Reading database ... 239480 files and directories currently installed.)
Preparing to unpack .../hcfft-master-47ee790-Linux.deb ...
Unpacking hcfft (0.1.1) ...
Setting up hcfft (0.1.1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...

**Comment by whchung** [comment]
@xyang2013 Thanks for your questions. 

For Question 1, I've modified the documentation to be more clear for Python 3-based systems:

https://github.com/ROCmSoftwarePlatform/tensorflow/blob/rocm-v1/rocm_docs/tensorflow-install-basic.md
https://github.com/ROCmSoftwarePlatform/tensorflow/blob/rocm-v1/rocm_docs/tensorflow-build-from-source.md

For Question 2, quite a few FFT-based convolution kernels are actually implemented in `MIOpen`, so you shouldn't worry the weird messages in building `hcfft`.  In fact we are about to update PIP packages & documentation in the next couple of days to completely remove dependency to `hcfft`.

**Comment by xyang2013** [comment]
@whchung Thank you. I am trying to run some of my testing code. So far it is good. By the way, when are you expecting RNN will be available with this version?

**Comment by whchung** [comment]
@xyang2013 all I can say now is we are very close. You can see in this repository we already have a `rocm-v1-rnn` branch sitting there with multi-layer RNN logic there.  + @dagamayank  for RNN in `MIOpen`.

**Comment by gstoner** [comment]
@xyang2013  Soon,  just waiting on MIOpen 1.3 to role out

**Comment by xyang2013** [comment]
@gstoner Thank you

**Comment by whchung** [comment]
@xyang2013 I'll close the issue hereby. BTW LSTM/GRU will indeed be supported in the upcoming `MIOpen` 1.3 release.
