### ISSUE TITLE
XLA JIT significantly slower than without XLA

### ISSUE THREAD

**Issue by dibyendudas0708** [ROCmSoftwarePlatform/tensorflow#28]
When using XLA JIT and targeting the GPU, performance is significantly slower than when run without XLA on the same GPU. The frozen model and the code to run have already been shared. You can re-create the issue using the same model/code on Polaris/Vega. The performance drop is of the order of 15x-30x. My guess is that the auto tuner for conv may not be working (or not working correctly) under XLA.

**Comment by dagamayank** [comment]
@dibyendudas0708 XLA has been known to be slower than native path at least in the TF v1.3 realm. Feel free to create PRs if you find the fix for this.

**Comment by whchung** [comment]
@dibyendudas0708 I've got the test data and program from you. Please kindly specify fool-proof steps to reproduce the issue, as well as dependent PIP packages.

**Comment by mei-ye** [comment]
Note that Tensorflow doc does not claim that XLA is faster, it says it might be faster or slower.Also from a paper on TVM, XLA has the lowest performance compared to hand-coded libraries and auto-kernel generation + auto-tuning techniques.


-Mei
    On Monday, April 2, 2018, 1:07:06 PM PDT, Wen-Heng (Jack) Chung <notifications@github.com> wrote:  
 
 
@dibyendudas0708 I've got the test data and program from you. Please kindly specify fool-proof steps to reproduce the issue, as well as dependent PIP packages.

**Comment by whchung** [comment]
With `HIP_TRACE_API=2` we can see `MIOpen` kernels are still in use when XLA is on. This suggests poor kernels emitted by XLA.

**Comment by dibyendudas0708** [comment]
You need to install opencv for cv2. I have also modified the test_dnet.py code to remove the dependence on PIL (which is not required). Please download the modified file and have a look. Thx.

**Comment by whchung** [comment]
As profiling results show large amount of time spent in LLVM APIs, it suggest JIT kernel itself be an expensive operation in TF 1.3.
And AOT XLA in 1.3 works only on CPU for now.

I'll close this ticket for now and revisit the performance of XLA when we re-sync with tip of upstream TensorFlow.
