### ISSUE TITLE
Release date for MIOpen 1.3

### ISSUE THREAD

**Issue by xyang2013** [ROCmSoftwarePlatform/tensorflow#29]
Hi, could you give an estimated date? I am currently working on a project that requires RNN. If you are only going to release it much later, I would need to consider using AWS instead of my workstation with Vega graphic cards. Thank you.

**Comment by gstoner** [comment]
1.3 MIOpen Released on Friday

**Comment by whchung** [comment]
+ @jedwards-AMD  for awareness

@xyang2013 as @gstoner mentioned, `MIOpen` 1.3.0 was released on Friday:

https://github.com/ROCmSoftwarePlatform/MIOpen/releases/tag/1.3.0


But its binary package are not placed at `repo.radeon.com` so you can't install it with `apt update`.

Also I'll need to do the followings:
- merge `rocm-v1-rnn` branch into `rocm-v1` branch
- rebuild TensorFlow and publish updated PIP packages onto `repo.radeon.com` with the help of @jedwards-AMD

**Comment by xyang2013** [comment]
@gstoner @whchung Thank you. Really hope the updated binary package will be available soon as I am in the middle of my project.

**Comment by whchung** [comment]
@xyang2013 binary packages are available pending some final reviews before we place them on `repo.radeon.com`. 

+ @jedwards-AMD / @gstoner for awareness

**Comment by xyang2013** [comment]
@whchung Thanks. I will try that.

**Comment by mei-ye** [comment]
The RNN in the branch is to support APIs in python module "cudnn_rnn_ops".   RNN cell APIs are taking the CPU path. It should work.  If you are not using "cudnn_rnn_ops", there is no need tor you to wait.
-Mei
    On Sunday, April 1, 2018, 8:20:26 PM PDT, xyang2013 <notifications@github.com> wrote:  
 
 
@whchung Thanks. I will try that.

**Comment by xyang2013** [comment]
@mei-ye Thanks. I like to use "cudnn_rnn_ops" as any speedup might be helpful, though I understand for RNNs the speedup of using GPU over CPU can be less prominent.

**Comment by jedwards-AMD** [comment]
The ROCm 1.7.1 repo was updated with the 1.3 version of MIOpen today.

**Comment by whchung** [comment]
@jedwards-AMD PIP whl packages at http://repo.radeon.com/rocm/misc/tensorflow/ is still dated on 3/25 so it's without RNN / `MIOpen` 1.3. Could you help revise that with the new packages I provided? Thanks.

**Comment by xyang2013** [comment]
@whchung Once the packages in http://repo.radeon.com/rocm/misc/tensorflow/ are updated, if I follow the basic installation, RNN / MIOpen 1.3 should be installed. Is it right?

**Comment by whchung** [comment]
Yes. I'm still waiting for @jedwards-AMD to revise PIP wheels on http://repo.radeon.com/rocm/misc/tensorflow/ .

**Comment by jedwards-AMD** [comment]
They have been uploaded and the version of MIOpen in ROCm 1.7.1 was updated as well.
