### ISSUE TITLE
Is there a tool similar to Nvidia-SMI for showing GPU utilisation?

### ISSUE THREAD

**Issue by xyang2013** [ROCmSoftwarePlatform/tensorflow#36]
I am testing some code that does multi-gpu training. Is there a tool that is similar to nvidia-smi? Thanks

**Comment by whchung** [comment]
@xyang2013 try `rocm-smi` and `rocminfo`. They are all installed in ROCm stack.

You can find the projects at:
https://github.com/RadeonOpenCompute/ROC-smi
https://github.com/RadeonOpenCompute/rocminfo
