### ISSUE TITLE
Numpy version mismatch

### ISSUE THREAD

**Issue by Mandrewoid** [ROCmSoftwarePlatform/tensorflow#41]
If you do a clean install according to the basic install docs, you will get a numpy version mismatch because the numpy version installed by apt is old. (At least in the python3 version)
The error looks like this:
>>> import tensorflow
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa

Problem can be solved by pip3 install numpy --upgrade

**Comment by whchung** [comment]
@parallelo please help check `numpy` version building new pip whl for ROCm 1.7.2 , and upcoming releases

**Comment by parallelo** [comment]
FYI - We're pushing out new whl files, and we'll also probably update the public docker images now that ROCm 1.7.2 is live. I'll also update the documentation.  Thanks for the heads-up.

**Comment by sclarkson** [comment]
The numpy minimum version in setup.py should be the same version that you use in your build environment. Ideally, you should use 1.11 in your build environment, as that is what is shipped with Ubuntu 16.04.

**Comment by whchung** [comment]
Closing this issue as the new PIP whl packages were published last week.
