### ISSUE TITLE
Hate to be that guy, but...

### ISSUE THREAD

**Issue by boxerab** [ROCmSoftwarePlatform/tensorflow#49]
Now that ROCm 1.7.2 is released, what is ETA for tensorflow update ?

Thanks!

**Comment by whchung** [comment]
@boxerab before we update PIP packages on `repo.radeon.com`, please take a sneak peek at:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/tree/develop-upstream

**Comment by boxerab** [comment]
1.8 .... Nice!!  Also, there is a windows build. Does that mean what I think it means ?

**Comment by boxerab** [comment]
Ahh, CPU only. Oh well.

**Comment by whchung** [comment]
The port for 1.8 is still in very early stage yet with nothing really running on GPU yet. That said things should change rather rapidly in the next couple of weeks as we check in implementation for 1.8.

**Comment by boxerab** [comment]
Sounds good. Can't wait.
