### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by GhostChild** [ROCmSoftwarePlatform/tensorflow#51]
I use rocm/tensorflow docker container 
import tensorflow error
![image](https://user-images.githubusercontent.com/22742106/39408378-ccd13eb8-4c07-11e8-9f6e-72848f0515e4.png)

Illegal instruction (core dumped)

I think my CPU is E3-1245V2 ,It not have AVX2 instruction
maybe you build this image use AVX2 or more instruction
but I'm not sure.

My PC:
CPU E3-1245V2
GPU AMD RX480
system Archlinux
docker 18-04 CE

**Comment by parallelo** [comment]
Hi @GhostChild - Thanks for the heads-up.  Can you send the results of the following commands?
```
tail /proc/cpuinfo | grep flags
echo | gcc -### -E - -march=native
```
The initial (not optimal) workaround is to rebuild TF inside the container.

**Comment by GhostChild** [comment]
`➜  ~ tail /proc/cpuinfo | grep flags
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt ibpb ibrs stibp dtherm ida arat pln pts

➜  ~ echo | gcc -### -E - -march=native
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.3.1 20180312 (GCC) 
COLLECT_GCC_OPTIONS='-E' '-march=native'
 /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/cc1 -E -quiet - "-march=ivybridge" -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-sgx -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx5124fmaps -mno-avx5124vnniw -mno-clwb -mno-mwaitx -mno-clzero -mno-pku -mno-rdpid --param "l1-cache-size=32" --param "l1-cache-line-size=64" --param "l2-cache-size=8192" "-mtune=ivybridge"
COMPILER_PATH=/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../lib/:/lib/../lib/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-march=native'
`

this is the results

**Comment by parallelo** [comment]
FYI - We've got a fix coming your way.  We're pushing out new whl files, and we'll also probably update the public docker images now that ROCm 1.7.2 is live.  Stay tuned.

**Comment by GhostChild** [comment]
thx, I'm looking forward to the new version.

**Comment by whchung** [comment]
@GhostChild the PIP packages were revised earlier today

**Comment by whchung** [comment]
Closing this issue as new PIP whl packages were published built with `-march=haswell` which is the minimum supported CPU arch for ROCm.
