### ISSUE TITLE
Wheel targeting python 3

### ISSUE THREAD

**Issue by Mandrewoid** [ROCmSoftwarePlatform/tensorflow#6]
Thanks for the heads up about the release @sunway513 I think a high % of users would agree with me, a build for python3 is important. I'll try and give it a shot and build from source myself but I won't be able to get to it until later this week, probably Friday. 

In the meantime, for whoever does the building that is hosted in: http://repo.radeon.com/rocm/misc/tensorflow/
Is the reason only the python 2.7 version is hosted because there are errors in building the 3.5 .whl? or is it merely an oversight? I was under the impression that bazel "automagically" would build both but I could be mistaken. Perhaps the other wheel is built somewhere on the dev server, and just needs to be upload to repo.

**Comment by whchung** [comment]
@Mandrewoid I've made a commit to build wheel for python3
https://github.com/ROCmSoftwarePlatform/tensorflow/blob/rocm-v1/build_python3

actual wheel files would be uploaded after validation

**Comment by whchung** [comment]
@Mandrewoid the package is now published at:
http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.3.0-cp35-cp35m-linux_x86_64.whl
