### ISSUE TITLE
Multi GPUs supporting

### ISSUE THREAD

**Issue by reger-men** [ROCmSoftwarePlatform/tensorflow#61]
Hello,

I tried to run the tutorial example of tensorflow  [cifar10](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py)
with batch_size = 6048 on P47 machine with 4 GPUs MI25 (16Gb x 4). The training doestt start and I got the error below:
`2018-05-15 19:38:29.177804: F tensorflow/stream_executor/rocm/rocm_dnn.cc:1603] Check failed: status == miopenStatusSuccess (7 vs. 0)Unable to find a suitable algorithm for doing forward convolution`
It seem like, that the current Rocm tensorflow implementation in this cases doesnt support the multi GPU training.

PS. I run the same script on multi GPU machine ( 2 x GTX 1080) and it work fine.

Could you please take a look at it. Thanks in advance.

### System information
- **OS Platform and Distribution (Linux Ubuntu 16.04 with ROCm 1.8)**
- **TensorFlow installed from: binary**
- **TensorFlow version: 1.3**
- **Python version: 2 and 3**
- **CUDA/cuDNN version: 9/8**
- **GPU model and memory: MI25 16Gb**
- **Exact command to reproduce: `python3 cifar10_multi_gpu_train.py --num_gpus=4`**

**Comment by whchung** [comment]
@parallelo could you help take a look at this before @7SK steps in. we run mGPU training all the time.

**Comment by parallelo** [comment]
Closing for now, but please re-open if you have questions/comments/concerns.

**Comment by reger-men** [comment]
now Iam able to run the training "on multi_gpus", but as you can see, there is no profit from multi gpu mode. The number of examples per second remains the same in both cases (with only 1 GPU and with 4 GPUs).


`root@38ac92e3b76c:/root# python models/tutorials/image/cifar10/cifar10_multi_gpu_train.py --num_gpus=1 --batch_size=5000`
![pastedimage](https://user-images.githubusercontent.com/8779942/41169515-86b02956-6b49-11e8-9e26-322691b13ed3.png)


`root@38ac92e3b76c:/root# python models/tutorials/image/cifar10/cifar10_multi_gpu_train.py --num_gpus=4 --batch_size=5000`
![2222222222](https://user-images.githubusercontent.com/8779942/41169525-91431bc6-6b49-11e8-97aa-0a74b72c0415.png)

**Comment by whchung** [comment]
In ROCm 1.8.0 there is a perf regression caused in HIP runtime and a fix was merged in recently ( https://github.com/ROCm-Developer-Tools/HIP/pull/491 ). Please expect it be adopted in ROCm 1.8.2 release.

**Comment by computingdolas** [comment]
Try this ./hipBusBandwidth --p2p to see if your system supports it ?
