### ISSUE TITLE
PyTorch and OpenAI supports

### ISSUE THREAD

**Issue by xyang2013** [ROCmSoftwarePlatform/tensorflow#62]
Hi, I know I raised this issue before. I have been working on an RNN problem for a while. I think with Tensorflow, it can be hard to modify network architectures sometimes. In comparison, PyTorch seems to be easier to complete such tasks. I think Tensorflow is good for production use, e.g. distributed training (with kubernetes etc). But for prototyping, I think PyTorch is better suited (e.g. easier to debug). As such, I am considering switching to Nvidia cards for now as I can't use PyTorch with my Vega FE cards at the moment.

In addition, I don't know whether I can use OpenAI's gym for reinforcement learning with my Vega FE cards.

**Comment by briansp2020** [comment]
Have you tried https://github.com/wsttiger/pytorch/commits/sending_pr?
I don't have Vega. So, I don't know how functional it is...

**Comment by whchung** [comment]
/cc @petrex for awareness

To my understanding ROCm port of PyTorch and Caffe2 are already in the process of upstreaming and since upstream PyTorch and Caffe2 have been merged into a single project we've been working with our partner to do the same on ROCm platform. I'd like to invite @petrex to weigh in.

**Comment by petrex** [comment]
@xyang2013 Pytoch 1.0 is coming with native Vega support. Stay tuned.
Theoretically, you can do anything with your Vega FE.

**Comment by whchung** [comment]
Closing this ticket. @xyang2013 feel free to re-open it when you see fit.
