### ISSUE TITLE
When tensorflow 1.4.1 or above?

### ISSUE THREAD

**Issue by rjfnobre** [ROCmSoftwarePlatform/tensorflow#63]
First of all, congratulations for you excellent work!

From what I understood, your version is based on tensorflow 1.3.

Are you planing to migrate to a more recent version? When?

Regards

**Comment by whchung** [comment]
Please check https://github.com/ROCmSoftwarePlatform/tensorflow-upstream

develop-upstream branch contains port to ROCm to TF 1.8+. It is still under development but is already functional. We are doing more testing now and would deprecate the current repository after we feel more comfortable about the new version

**Comment by briansp2020** [comment]
@whchung What milestones do you need to hit before you release 1.8+ whl built from that branch? Do you see it happening by the time ROCm 1.9 is released?

**Comment by whchung** [comment]
We’ll release TF 1.8 ROCm whl after:

- polish patches to Eigen
- integrate rocPRIM which is a functional equivalent for CUB
- pass tests we’ve collected thus far
- works with upcoming ASICs 

The release would happen prior to ROCm 1.9 so it’s possible to use it with ROCm 1.8.0 or 1.7.2. Most likely it’ll be aligned with ROCm 1.8.1 where we address a few perf issues encountered in ROCm 1.8.0

**Comment by whchung** [comment]
Closing the ticket hereby.
