### ISSUE TITLE
new wheel throws "not a supported wheel on this platform."

### ISSUE THREAD

**Issue by isaac-rstor** [ROCmSoftwarePlatform/tensorflow#67]
OS:  Ubuntu 16.04; also tested inside a singularity containter
TF install attempted from new wheels (http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.3.0-cp27-cp27m-manylinux1_x86_64.whl)
Python: Python 2.7.12, 2.7.14
Pip: 9.0.3, 10.0.1

### Describe the problem
New wheel rejected due to error:  
tensorflow-1.3.0-cp27-cp27m-manylinux1_x86_64.whl is not a supported wheel on this platform.

Additionally, is there access to legacy wheels?  That would be great.

**Comment by isaac-rstor** [comment]
provisional solution:  rename the wheel file to tensorflow-1.3.0-cp27-cp27mu-linux_x86_64.whl

**Comment by parallelo** [comment]
Thanks for the heads-up -- much appreciated.  We switched over to using `tensorflow/tools/ci_build/builds/pip.sh`, so the whl names have changed.  The python2 whl doesn't currently work, but the python3 whl does.  

We'll get it fixed soon on repo.radeon.com.  We'll be updating with this (note the `cp27mu` vs `cp27u`):  
```
tensorflow-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl
```

**Comment by parallelo** [comment]
All set.  Uploaded a new whl this morning.  
```
wget http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl
pip uninstall tensorflow
pip install ./tensorflow-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl
```
Closing the ticket.  Please feel free to re-open if there continues to be challenges.  Thanks again for letting us know about the issue.
