### ISSUE TITLE
Can't load tensorflow runtime

### ISSUE THREAD

**Issue by zgu153522** [ROCmSoftwarePlatform/tensorflow#7]
On Ubuntu 16.04, with ROCm 1.7.1 installed, I ran through tensorflow install instructions but then found a problem with importing tensorflow and libhipfft.so:

 python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libhipfft.so: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by sunway513** [comment]
Hi @zgu153522 , please try to build and install hcfft manually:
```
git clone https://github.com/ROCmSoftwarePlatform/hcFFT.git ~/hcfft
cd ~/hcfft && bash build.sh && dpkg -i ~/hcfft/build/*.deb
```

**Comment by whchung** [comment]
We are working on getting rid of the dependency to `hcfft` now. Should be ready in the next couple of days.

**Comment by zgu153522** [comment]
@sunway513 I installed hcfft manually and now there's another dependency:

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /opt/rocm/bin/../lib/librocblas.so.0: undefined symbol: _ZN8hip_impl22hipLaunchKernelGGLImplEmRK4dim3S2_jP12ihipStream_tPPv


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by sunway513** [comment]
What's the output of the following command?
`apt --installed list | grep rocblas`

**Comment by zgu153522** [comment]
@sunway513 
apt --installed list | grep rocblas

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

rocblas/Ubuntu 16.04,now 0.12.0.0 amd64 [installed,automatic]

**Comment by sunway513** [comment]
Thanks @zgu153522 , could you try our pre-built [docker image](https://hub.docker.com/r/rocm/tensorflow/) and see if that can work?

The rocblas version installed should be correct, but I could not reproduce your issue locally. 
If the docker image can work, you will then be able to do a side by side comparison to figure out the configuration issues on your bare metal setup.

**Comment by zgu153522** [comment]
@sunway513 I get:
sudo docker run -it --device=/dev/kfd --device=/dev/dri --group-add video rocm/tensorflow
root@3d702f7bf730:/root/tensorflow# python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
ImportError: No module named pywrap_tensorflow_internal


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by sclarkson** [comment]
@zgu153522 You need to change directories. Go up a level.

https://stackoverflow.com/questions/35953210/error-running-basic-tensorflow-example

**Comment by zgu153522** [comment]
Thanks, it's now working in the docker.  Any instructions to do the side-by-side comparison to figure out what's wrong with my bare metal setup?

**Comment by boxerab** [comment]
I am getting the same error, by the way.

**Comment by sunway513** [comment]
@boxerab did you build and install hcfft from source?

**Comment by boxerab** [comment]
no I didn't.  I am using 1.7.1 RC 4 .deb packages.

**Comment by sunway513** [comment]
Please upgrade your ROCm environment to ROCm1.7.1, and follow exact steps listed here:
`https://github.com/ROCmSoftwarePlatform/tensorflow/blob/rocm-v1/rocm_docs/tensorflow-install-basic.md`

**Comment by boxerab** [comment]
If I run `sudo apt update` will I get 1.7.1 ?

**Comment by sunway513** [comment]
@boxerab , here's the document for upgrade:
`https://github.com/RadeonOpenCompute/ROCm#installing-from-amd-rocm-repositories`

**Comment by sunway513** [comment]
@zgu153522 , thanks for updating. 
If docker contain can work, it means you have issues with your user bits configurations. 

For such issue, I would recommend you start by comparing the following software versions between docker and bare metal:
`apt --installed list | grep 'rocm\|hsa\| hip\|miopen\|rocblas\|rocrand'`

**Comment by zgu153522** [comment]
Suspicious discrepancy:
Bare metal:
rocblas/now 0.12.0.0 amd64 [installed,local]
rocm-clang-ocl/now 0.2.0-83527dd amd64 [installed,local]

Docker:
rocblas/now 0.10.4.15 amd64 [installed,local]
rocm-clang-ocl/now 0.3.0-c1b678e amd64 [installed,local]

Also the docker doesn't have rocm-dkms

**Comment by boxerab** [comment]
@sunway513  thanks, it looks like it is working now that I built hcfft from source.

BTW, tensorflow 1.3 only works with python 2.x. Is that correct ? Doesn't work with python 3 ?

**Comment by sunway513** [comment]
@zgu153522 , we just have refreshed the docker image, please pull it and compare again:
`sudo docker pull rocm/hiptensorflow:rocm1.7.1`

**Comment by zgu153522** [comment]
@sunway513 
Discrepancies:
Bare metal:
hsakmt-rocm-dev/now 2.0.0 amd64 [installed,local]
rocm-clang-ocl/now 0.2.0-83527dd amd64 [installed,local]
rocm-dkms/now 1.7.137 amd64 [installed,local]
rocm-smi/now 1.0.1 amd64 [installed,local]

Docker:
rocm-clang-ocl/now 0.3.0-c1b678e amd64 [installed,local]
rocm-smi/now 1.0.0-38-g3fe4e0c amd64 [installed,local]

I did update of rocm-clang-ocl to 0.3.0 but still get:
python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /opt/rocm/bin/../lib/librocblas.so.0: undefined symbol: _ZN8hip_impl22hipLaunchKernelGGLImplEmRK4dim3S2_jP12ihipStream_tPPv


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> quit()

**Comment by sclarkson** [comment]
Run `ldconfig -p | grep hip_hcc`. If that shows nothing, try running `apt-get install --reinstall hip_hcc`

**Comment by zgu153522** [comment]
@sclarkson 
ldconfig -p | grep hip_hcc
        libhip_hcc.so (libc6,x86-64) => /opt/rocm/lib/libhip_hcc.so

**Comment by sunway513** [comment]
@zgu153522 it's really difficult to triage the issue without access your system. What I would suggest is to either go for docker or prepare a clean Ubuntu system and follow our document from the start.

**Comment by chetant** [comment]
@zgu153522 I managed to get tensorflow 1.3 installed bare metal.
I was missing the hip_* packages.
```
$ apt --installed list | grep hip

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

hip_base/Ubuntu 16.04,now 1.5.18073 amd64 [installed,automatic]
hip_doc/Ubuntu 16.04,now 1.5.18073 amd64 [installed]
hip_hcc/Ubuntu 16.04,now 1.5.18073 amd64 [installed]
hip_samples/Ubuntu 16.04,now 1.5.18073 amd64 [installed,automatic]
hipblas/Ubuntu 16.04,now 0.10.1.0 amd64 [installed]
miopen-hip/Ubuntu 16.04,now 1.2.1-cf3d051 amd64 [installed]
```

**Comment by zgu153522** [comment]
@chetant Everything is working now - I had to update those hip packages.  Thanks!
