### ISSUE TITLE
Wheels are 404 

### ISSUE THREAD

**Issue by Mandrewoid** [ROCmSoftwarePlatform/tensorflow#76]
http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.3.0-cp35-cp35m-linux_x86_64.whl returns 404.
Same for the python 2 version.

**Comment by briansp2020** [comment]
http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl
http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.3.0-cp35-cp35m-manylinux1_x86_64.whl

**Comment by parallelo** [comment]
Thanks for letting us know.  There were some changes recently (as @briansp2020 correctly pointed out)

We updated the installation instructions to reflect the new names.  We recently switched to tensorflow's `ci_build` method of creating the whl files, and those have slightly different names.
https://github.com/ROCmSoftwarePlatform/tensorflow/blob/rocm-v1/rocm_docs/tensorflow-install-basic.md#install-tensorflow-rocm-port

Closing this ticket, but feel free to re-open it if you have ongoing challenges.
