### ISSUE TITLE
Training hung with GUI reboot

### ISSUE THREAD

**Issue by doody1986** [ROCmSoftwarePlatform/tensorflow#77]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
The latest code from branch rocm-v1
- **Python version**: 
Python 2.7.12
- **Bazel version (if compiling from source)**:
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778
- **ROCm version**:
ROCm 1.8.1
- **GPU model and memory**:
gfx900
- **Exact command to reproduce**:
In the root path of benchmark-imagenet from tensorflow

```
MODEL=alexnet
NGPUS=1
BATCH_SIZE=4
ITERATIONS=10
python ./scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model=${MODEL} \
  --data_name=cifar10 --data_dir=<path_to_cifar_data_for_py> --train_dir=<path_to_checkpoint> \
  --save_summaries_steps 1 --save_model_secs=1 --print_training_accuracy=True \
  --variable_update=parameter_server --local_parameter_device=cpu --num_batches=${ITERATIONS} \
  --num_gpus=${NGPUS} --batch_size=${BATCH_SIZE} 2>&1 | tee <path_to_log>/tf-cifar.txt
```

### Describe the problem

I am running the experiments using benchmark-imagenet from tensorflow but with CIFAR10 data. it is supposed to be supported. However, when running above script, the system hung after the GPU device is created. After a while, the GUI is rebooted.

### Source code / logs

I didn't modify any code and the log output is as below.

```
2018-06-06 15:50:18.893148: W tensorflow/stream_executor/rocm/rocm_driver.cc:405] creating context when one is currently active; existing: 0x7f9a401600e0
2018-06-06 15:50:18.893289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] Found device 0 with properties:  
name: Device 687f  
AMDGPU ISA: gfx900  
memoryClockRate (GHz) 1.622  
pciBusID 0000:43:00.0  
Total memory: 7.98GiB  
Free memory: 7.73GiB  
2018-06-06 15:50:18.893300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:928] DMA: 0   
2018-06-06 15:50:18.893304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:938] 0:   Y   
2018-06-06 15:50:18.893310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Device 687f, pci bus id: 0000:43:00.0)
```

**Comment by gstoner** [comment]
@doody1986 

Did you do this yet. 

If you Plan to Run with X11 - we are seeing X freezes under load

ROCm 1.8.1 a kernel parameter noretry has been set to 1 to improve overall system performance. However it has been proven to bring instability to graphics driver shipped with Ubuntu. This is an ongoing issue and we are looking into it.

Before that, please try apply this change by changing noretry bit to 0.

echo 0 | sudo tee /sys/module/amdkfd/parameters/noretry
Files under /sys won't be preserved after reboot so you'll need to do it every time.

One way to keep noretry=0 is to change /etc/modprobe.d/amdkfd.conf and make it be:

options amdkfd noretry=0

Once it's done, run sudo update-initramfs -u. Reboot and verify /sys/module/amdkfd/parameters/noretry stays as 0.

**Comment by doody1986** [comment]
@gstoner 

It works! Thanks very much!

**Comment by doody1986** [comment]
Close this issue as the solution works.
