### ISSUE TITLE
Link to tensorflow-upstream in github project description

### ISSUE THREAD

**Issue by uakfdotb** [ROCmSoftwarePlatform/tensorflow#85]
In addition to linking to https://github.com/ROCmSoftwarePlatform/tensorflow-upstream in README it would be good to link in the project description (currently "(DEPRECATED) TensorFlow 1.3.0 ROCm port"), otherwise at first glance it seems the project is just deprecated with no replacement.

**Comment by dagamayank** [comment]
Thank @uakfdotb. Done.
